# Generated by Django 3.2.6 on 2021-10-22 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Torrent',
        ),
    ]
